language: php

php:
  # see http://php.net/supported-versions.php
  - '7.1' # Until 1 Dec 2019
  - '7.2' # Until 30 Nov 2020
  - '7.3' # Until 6 Dec 2021


addons:
  apt:
    packages:
      - parallel

env:
  global:
    - PHPUNIT_VERSION=6.5.*
  matrix:
    # see https://phpunit.de/supported-versions.html
    # phpunit 7 until February 7, 2020
    - PHPUNIT_VERSION=7.1.*
    - PHPUNIT_VERSION=7.2.*
    - PHPUNIT_VERSION=7.3.*
    - PHPUNIT_VERSION=7.4.*
    - PHPUNIT_VERSION=7.5.*
    - PHPUNIT_VERSION=8.0.*
    - PHPUNIT_VERSION=8.1.*
    - PHPUNIT_VERSION=8.2.*

matrix:
  include:
    # Intermediate version tests due to unstable SemVer
    - php: '7.2'
      env: PHPUNIT_VERSION="~8"
  # in the process to achieve support
  # allow_failures:
  #  - php: 'nightly-7.4'
  #  - php: 'nightly-8.0'
  exclude:
    - php: '7.1'
      env: PHPUNIT_VERSION=8.0.*
    - php: '7.1'
      env: PHPUNIT_VERSION=8.1.*
    - php: '7.1'
      env: PHPUNIT_VERSION=8.2.*

services:
  - mysql

before_install:
  # Try supporting other versions
  - composer require --update-with-dependencies phpunit/phpunit:$PHPUNIT_VERSION

install:
  - composer install

script:
  - composer validate --strict --no-check-lock
  - vendor/bin/phpunit
